//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace luiskart.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personaje()
        {
            this.PersonajesDibujos = new HashSet<PersonajeDibujo>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int AnimeId { get; set; }
    
        public virtual Anime Anime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonajeDibujo> PersonajesDibujos { get; set; }
    }
}
