//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luiskart.Compartido.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dibujo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dibujo()
        {
            this.PersonajesDibujos = new HashSet<PersonajeDibujo>();
        }
    
        public int Id { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public System.DateTime fechaIngreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonajeDibujo> PersonajesDibujos { get; set; }
    }
}
