//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luiskart.Compartido.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonajeDibujo
    {
        public int PersonajeId { get; set; }
        public int DibujoId { get; set; }
        public int Id { get; set; }
    
        public virtual Dibujo Dibujos { get; set; }
        public virtual Personaje Personaje { get; set; }
    }
}
